
services:

  api:
    image: [aws-account].dkr.ecr.us-west-1.amazonaws.com/example-api:api
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    depends_on:
      - mongo
      - kafka
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      x-aws-autoscaling:
        min: 1
        max: 5 #required
        cpu: 75
        # mem: - mutualy exlusive with cpu

  worker-health:
    image: [aws-account].dkr.ecr.us-west-1.amazonaws.com/example-api:worker
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
    depends_on:
      - mongo
      - kafka
    environment:
      TOPIC: health
    networks:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_db:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: root
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongo_db:
  kafka_data:
  zookeeper_data:
  zookeeper_log:

